In [31]:
import pandas as pd


csv_path = r"C:\Users\diana\OneDrive\Desktop\presales_data_sample.csv"
df = pd.read_csv(csv_path)


print(df.head())
print(df.columns)

   input_row_key                        input_company_name  \
0              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
1              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
2              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
3              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
4              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED

  input_main_country_code input_main_country input_main_region  \
0                      PK           Pakistan             Sindh
1                      PK           Pakistan             Sindh
2                      PK           Pakistan             Sindh
3                      PK           Pakistan             Sindh
4                      PK           Pakistan             Sindh

  input_main_city input_main_postcode input_main_street  \
0         Karachi                 NaN               NaN
1         Karachi                 NaN               NaN
2         Karachi                 NaN               NaN
3         Karachi                 NaN               NaN
4         Karachi                 NaN               NaN

  input_main_street_number                           veridion_id  ...  \
0                      NaN  26e22210-93e5-11eb-b997-8dd98d09cf25  ...
1                      NaN  01004641-1dd8-11ef-9268-316fc8e174dd  ...
2                      NaN  8266efc1-13e7-11ec-aa14-7bf90e1e10f1  ...
3                      NaN  0183f0b2-93e5-11eb-be5a-4f810ab55f2e  ...
4                      NaN  87bb7cde-93e4-11eb-8474-3bbe2d07207d  ...

                             twitter_url  \
0                                    NaN
1                                    NaN
2  https://twitter.com/Network24seven%20
3         https://twitter.com/emeriosoft
4          https://twitter.com/AsiaticPR

                                       instagram_url  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  https://www.instagram.com/asiaticpublicrelations/

                                        linkedin_url ios_app_url  \
0  http://www.linkedin.com/company/mnet-services-...         NaN
1                                                NaN         NaN
2    https://www.linkedin.com/company/51633612%20%20         NaN
3        https://www.linkedin.com/company/emeriosoft         NaN
4  https://www.linkedin.com/company/asiaticpublic...         NaN

  android_app_url                                        youtube_url  \
0             NaN                                                NaN
1             NaN                                                NaN
2             NaN                                                NaN
3             NaN                                                NaN
4             NaN  https://www.youtube.com/channel/UClKgHvHIuOu4K...

  tiktok_url                                       technologies  \
0        NaN  web servers: apache http server - 2 | javascri...
1        NaN                                                NaN
2        NaN                                                NaN
3        NaN  miscellaneous: popper | maps: google maps | pr...
4        NaN  miscellaneous: babel | javascript libraries: c...

                 created_at           last_updated_at
0  2020-02-25T14:47:51.000Z  2024-11-29T04:18:00.109Z
1  2024-05-29T16:24:11.019Z  2025-04-20T15:03:24.026Z
2  2021-09-12T05:28:48.000Z  2025-03-18T23:08:37.059Z
3  2020-05-03T12:33:22.000Z  2025-03-31T16:16:58.462Z
4  2020-02-19T03:58:25.000Z  2024-11-25T11:35:47.963Z

[5 rows x 76 columns]
Index(['input_row_key', 'input_company_name', 'input_main_country_code',
       'input_main_country', 'input_main_region', 'input_main_city',
       'input_main_postcode', 'input_main_street', 'input_main_street_number',
       'veridion_id', 'company_name', 'company_legal_names',
       'company_commercial_names', 'main_country_code', 'main_country',
       'main_region', 'main_city', 'main_postcode', 'main_street',
       'main_street_number', 'main_latitude', 'main_longitude', 'locations',
       'num_locations', 'company_type', 'year_founded', 'revenue',
       'revenue_type', 'employee_count', 'employee_count_type',
       'generated_description', 'generated_business_tags', 'short_description',
       'long_description', 'business_tags', 'naics_2022_primary_code',
       'naics_2022_primary_label', 'naics_2022_secondary_codes',
       'naics_2022_secondary_labels', 'main_business_category',
       'main_industry', 'main_sector', 'sics_codified_industry',
       'sics_codified_industry_code', 'sics_codified_subsector',
       'sics_codified_subsector_code', 'sics_codified_sector',
       'sics_codified_sector_code', 'sic_codes', 'sic_labels',
       'ibc_insurance_labels', 'isic_v4_codes', 'isic_v4_labels',
       'nace_rev2_codes', 'nace_rev2_labels', 'ibc_insurance_codes',
       'primary_phone', 'phone_numbers', 'primary_email', 'emails',
       'other_emails', 'website_url', 'website_domain', 'website_tld',
       'website_language_code', 'facebook_url', 'twitter_url', 'instagram_url',
       'linkedin_url', 'ios_app_url', 'android_app_url', 'youtube_url',
       'tiktok_url', 'technologies', 'created_at', 'last_updated_at'],
      dtype='object')

In [ ]:
relevant_columns = [
    "input_row_key",
    "input_company_name",
    "input_main_country_code",
    "input_main_country",
    "input_main_region",
    "input_main_city",
    "input_main_postcode",
    "input_main_street",
    "input_main_street_number",
    "company_name",
    "company_legal_names",
    "company_commercial_names",
    "main_country_code",
    "main_country",
    "main_region",
    "main_city",
    "main_postcode",
    "main_street",
    "main_street_number",
    "main_latitude",
    "main_longitude",
    "num_locations",
    "company_type",
    "year_founded",
    "veridion_id"
    
]

df_filtered = df[relevant_columns]
df_filtered.to_csv("filtered_companies.csv", index=False)
print("CSV-ul filtrat a fost salvat")

CSV-ul filtrat a fost salvat

In [41]:
print(df_filtered.head())

   input_row_key                        input_company_name  \
0              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
1              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
2              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
3              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED
4              0  24-SEVEN MEDIA NETWORK (PRIVATE) LIMITED

  input_main_country_code input_main_country input_main_region  \
0                      PK           Pakistan             Sindh
1                      PK           Pakistan             Sindh
2                      PK           Pakistan             Sindh
3                      PK           Pakistan             Sindh
4                      PK           Pakistan             Sindh

  input_main_city input_main_postcode input_main_street  \
0         Karachi                 NaN               NaN
1         Karachi                 NaN               NaN
2         Karachi                 NaN               NaN
3         Karachi                 NaN               NaN
4         Karachi                 NaN               NaN

  input_main_street_number                      company_name  ...  \
0                      NaN            New Millennium Network  ...
1                      NaN         Private Helipad Ali Villa  ...
2                      NaN          24seven Research Network  ...
3                      NaN                        EmerioSoft  ...
4                      NaN  Asiatic Public Relations Network  ...

          main_city main_postcode            main_street main_street_number  \
0           Karachi         74400                    NaN                NaN
1           Karachi         74400                    NaN                NaN
2         Faridabad        121001   Gurunanak Gali No. 3               3071
3               NaN         75300                    NaN                NaN
4  Karachi Division         75600  Nehr-e-Khayyam Street                NaN

  main_latitude main_longitude num_locations company_type year_founded  \
0           NaN            NaN           1.0      Private       2001.0
1           NaN            NaN           1.0          NaN          NaN
2     28.399705      77.286203           1.0      Private          NaN
3           NaN            NaN           2.0      Private       2012.0
4           NaN            NaN           3.0      Private       1963.0

                            veridion_id
0  26e22210-93e5-11eb-b997-8dd98d09cf25
1  01004641-1dd8-11ef-9268-316fc8e174dd
2  8266efc1-13e7-11ec-aa14-7bf90e1e10f1
3  0183f0b2-93e5-11eb-be5a-4f810ab55f2e
4  87bb7cde-93e4-11eb-8474-3bbe2d07207d

[5 rows x 25 columns]

In [43]:
import pandas as pd

df = pd.read_csv("filtered_companies.csv")


df_unique_companies_byvid = df.drop_duplicates(subset=["veridion_id"])


df_unique_companies_byvid .to_csv("filtered_unique_companies_by_veridionid.csv", index=False)

In [48]:
df_unique_companies_byname = df.drop_duplicates(subset=["company_name"])
df_unique_companies_byname.to_csv("filtered_unique_companies_by_name.csv", index=False)

In [ ]:
import pandas as pd

df = pd.read_csv("Filtered Companies .csv")
df['input_company_name'] = df['input_company_name'].str.lower().str.title()
df['company_name'] = df['company_name'].str.lower().str.title()

df.to_csv("Filtered_Companies_CleanCompanyName", index = False)

In [ ]:
import pandas as pd

df = pd.read_csv("Filtered Companies .csv")


df['input_company_name'] = df['input_company_name'].str.lower().str.capitalize()
df['company_name'] = df['company_name'].str.lower().str.capitalize()

df.to_csv("Filtered_Companies_Capitalized.csv", index=False)

In [ ]:
import pandas as pd
df = pd.read_csv("Filtered_Companies_Capitalized.csv")  


input_fields = ["input_main_country_code", "input_main_country", "input_main_region", 
                "input_main_city", "input_main_postcode", "input_main_street", "input_main_street_number"]

company_fields = ["main_country_code", "main_country", "main_region", 
                  "main_city", "main_postcode", "main_street", "main_street_number"]

def check_match(row):
    for input_field, company_field in zip(input_fields, company_fields):
        input_value = str(row[input_field]).strip().lower() if pd.notna(row[input_field]) else ""
        company_value = str(row[company_field]).strip().lower() if pd.notna(row[company_field]) else ""
        if input_value != company_value:
            return "unmatched"
    return "matched"


df["match_status"] = df.apply(check_match, axis=1)


df.to_csv("Sample_Companies.csv", index=False)

In [126]:
df["match_status"] = df.apply(check_match, axis=1)
print(df[["input_company_name", "match_status"]].head(10))

                         input_company_name match_status
0  24-seven media network (private) limited    unmatched
1  24-seven media network (private) limited    unmatched
2  24-seven media network (private) limited    unmatched
3  24-seven media network (private) limited    unmatched
4  24-seven media network (private) limited    unmatched
5                              2operate a/s    unmatched
6                              2operate a/s    unmatched
7                              2operate a/s    unmatched
8                              2operate a/s      matched
9                              2operate a/s      matched

In [22]:
max_allowed = 255
for col in text_columns:
    df1[col] = df1[col].apply(lambda x: str(x)[:max_allowed] if pd.notna(x) else x)

df1.to_csv("Sample_Companies_Clean.csv", index=False, encoding="utf-8")

In [ ]:
cols_to_keep = [
    "input_row_key",
    "input_company_name",
    "company_name",
    "company_legal_names",
    "company_commercial_names",
    "main_country_code",
    "main_country",
    "year_founded",
    "company_type",
    "veridion_id",
    "match_status"
]

df1 = df1[cols_to_keep] 
df1.to_csv("Sample_Companies_Final.csv", index=False, encoding="utf-8")